const fs = require('fs');
const path = require('path');
const WEBSITES_PATH = 'f:/collegereviewz.com/scripts/college_websites.json';

const newMappings = {
    // Batch 19-20
    "ST. MARY'S ENGINEERING COLLEGE": "stmarys.ac.in",
    "ST. PETER'S ENGINEERING COLLEGE": "spechyd.ac.in",
    "TKR COLLEGE OF ENGINEERING AND TECHNOLOGY": "tkrcet.ac.in",
    "TEEGALA KRISHNA REDDY ENGINEERING COLLEGE": "tkrec.ac.in",
    "VAAGDEVI COLLEGE OF ENGINEERING": "vaagdevi.edu.in",
    "VASAVI COLLEGE OF ENGINEERING": "vce.ac.in",
    "VIGNAN INSTITUTE OF TECHNOLOGY AND SCIENCE": "vignanits.ac.in",
    "VIGNAN'S FOUNDATION FOR SCIENCE TECHNOLOGY AND RESEARCH": "vignan.ac.in",
    "ADITYA ENGINEERING COLLEGE": "aec.edu.in",
    "ADITYA INSTITUTE OF TECHNOLOGY AND MANAGEMENT": "adityatekkali.edu.in",
    "ANDHRA UNIVERSITY COLLEGE OF ENGINEERING": "andhrauniversity.edu.in",
    "ANIL NEERUKONDA INSTITUTE OF TECHNOLOGY AND SCIENCES": "anits.edu.in",
    "ANNAMACHARYA INSTITUTE OF TECHNOLOGY AND SCIENCES": "aitsrajampet.ac.in",
    "AUDISANKARA COLLEGE OF ENGINEERING & TECHNOLOGY": "audisankara.ac.in",
    "BAPATLA ENGINEERING COLLEGE": "becbapatla.ac.in",
    "BVC ENGINEERING COLLEGE": "bvcgroup.in",
    // Batch 21-22
    "CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY": "cbit.ac.in",
    "G.M.R. INSTITUTE OF TECHNOLOGY": "gmrit.org",
    "GAYATRI VIDYA PARISHAD COLLEGE OF ENGINEERING": "gvpce.ac.in",
    "G. PULLA REDDY ENGINEERING COLLEGE": "gprec.ac.in",
    "GIET ENGINEERING COLLEGE": "giet.ac.in",
    "GODAVARI INSTITUTE OF ENGINEERING AND TECHNOLOGY": "giet.ac.in",
    "GUDLAVALLERU ENGINEERING COLLEGE": "gecgudlavalleru.ac.in",
    "JNTUA COLLEGE OF ENGINEERING ANANTHAPURAMU": "jntuacep.ac.in",
    "JNTUK COLLEGE OF ENGINEERING KAKINADA": "jntukcek.ac.in",
    "K.L. UNIVERSITY": "kluniversity.in",
    "LAKIREDDY BALI REDDY COLLEGE OF ENGINEERING": "lbrce.ac.in",
    "M.V.G.R. COLLEGE OF ENGINEERING": "mvgrce.edu.in",
    "MADANAPALLE INSTITUTE OF TECHNOLOGY & SCIENCE": "mits.ac.in",
    "LENDI INSTITUTE OF ENGINEERING AND TECHNOLOGY": "lendi.org",
    // Batch 23-24
    "NATIONAL INSTITUTE OF TECHNOLOGY": "nitandhra.ac.in",
    "NRI INSTITUTE OF TECHNOLOGY": "nriit.edu.in",
    "PACE INSTITUTE OF TECHNOLOGY AND SCIENCES": "pace.ac.in",
    "PRAGATI ENGINEERING COLLEGE": "pragati.ac.in",
    "PRASAD V. POTLURI SIDDHARTHA INSTITUTE OF TECHNOLOGY": "pvpsiddhartha.ac.in",
    "R.V.R. & J.C.COLLEGE OF ENGINEERING": "rvrjcce.ac.in",
    "RAGHU ENGINEERING COLLEGE": "raghuenggcollege.com",
    "RAJEEV GANDHI MEMORIAL COLLEGE OF ENGINEERING & TECHNOLOGY": "rgmcet.edu.in",
    "SAGI RAMAKRISHNAM RAJU ENGINEERING COLLEGE": "srkrec.ac.in",
    "SIDDHARTHA INSTITUTE OF ENGINEERING & TECHNOLOGY": "siet.ac.in",
    "SREE VIDYANIKETHAN ENGINEERING COLLEGE": "svec.education",
    "SWARNANDHRA COLLEGE OF ENGINEERING & TECHNOLOGY": "swarnandhra.ac.in",
    "V.R.SIDDHARTHA ENGINEERING COLLEGE": "vrsiddhartha.ac.in",
    "VIGNAN'S INSTITUTE OF INFORMATION TECHNOLOGY": "vignaniit.edu.in",
    "VIGNAN'S LARA INSTITUTE of TECHNOLOGY & SCIENCE": "vignanlara.org",
    "VIGNANA BHARATHI INSTITUTE OF TECHNOLOGY": "vbithyd.ac.in",
    // Batch 25-26
    "ACHARYA INSTITUTE OF TECHNOLOGY": "acharya.ac.in",
    "ACHARYA NAGARJUNA UNIVERSITY COLLGE OF ENGINEERING AND TECHNOLOGY": "anu.ac.in",
    "ADICHUNCHANAGIRI INSTITUTE OF TECHNOLOGY": "aitckm.edu.in",
    "ALAGAPPA CHETTIAR GOVERNMENT COLLEGE OF ENGINEERING AND TECHNOLOGY": "accet.edu.in",
    "ALLIANCE UNIVERSITY": "alliance.edu.in",
    "ALVAS INSTITUTE OF ENGINEERING AND TECHNOLOGY": "aiet.org.in",
    "AMRITA VISHWA VIDYAPEETHAM": "amrita.edu",
    "AMRUTVAHINI COLLEGE OF ENGINEERING": "avcoe.org",
    "ANANTRAO PAWAR COLLEGE OF ENGINEERING & RESEARCH": "abmspcoer.org",
    "ANNAMALAI UNIVERSITY": "annamalaiuniversity.ac.in",
    "SRM UNIVERSITY AP (ANDHRA PRADESH)": "srmap.edu.in",
    "ARMY INSTITUTE OF TECHNOLOGY": "aitpune.com",
    "ASANSOL ENGINEERING COLLEGE": "aecwb.edu.in",
    "ASSAM DON BOSCO UNIVERSITY": "dbuniversity.ac.in",
    "ASSAM DOWN TOWN UNIVERSITY": "adtu.in",
    "ASSAM ENGINEERING COLLEGE": "aec.ac.in",
    "ARYABHATTA KNOWLEDGE UNIVERSITY": "akubihar.ac.in",
    "ARKA JAIN UNIVERSITY": "arkajainuniversity.ac.in",
    // Batch 27-28
    "ATME COLLEGE OF ENGINEERING": "atme.in",
    "B.M.S. COLLEGE OF ENGINEERING": "bmsce.ac.in",
    "B.N.M. INSTITUTE OF TECHNOLOGY": "bnmit.org",
    "B.S.ABDUR RAHMAN CRESCENT INSTITUTE OF SCIENCE & TECHNOLOGY": "crescent.education",
    "B.V.V. SANGHA'S BASAVESHWAR ENGINEERING COLLEGE (AUTONOMOUS) BAGALKOT": "becbgk.edu",
    "BABARIA INSTITUTE OF TECHNOLOGY": "bitsuraj.ac.in",
    "BABASAHEB BHIMRAO AMBEDKAR UNIVERSITY": "bbau.ac.in",
    "BABU BANARASI DAS UNIVERSITY": "bbduniversity.ac.in",
    "BALLARI INSTITUTE OF TECHNOLOGY & MANAGEMENT": "bitm.edu.in",
    "BANASTHALI VIDYAPITH": "banasthali.org",
    "BANGALORE INSTITUTE OF TECHNOLOGY": "bit-bangalore.edu.in",
    "BANNARI AMMAN INSTITUTE OF TECHNOLOGY": "bitsathy.ac.in",
    "BIET": "bietdvg.edu",
    "BARKATULLAH UNIVERSITY INSTITUTE OF TECHNOLOGY": "bhopaluniversity.ac.in",
    "BEANT COLLEGE OF ENGINEERING & TECHNOLOGY": "sbssugsp.ac.in",
    "BENGAL COLLEGE OF ENGINEERING AND TECHNOLOGY": "bcet.ac.in",
    "BHARATI VIDYAPEETH UNIVERSITY": "bvuniversity.edu.in",
    "BIJU PATNAIK UNIVERSITY OF TECHNOLOGY": "bput.ac.in",
    "BIRLA INSTITUTE OF TECHNOLOGY MESRA": "bitmesra.ac.in",
    "BIRSA INSTITUTE OF TECHNOLOGY SINDRI": "bitsindri.ac.in",
    "BMS INSTITUTE OF TECHNOLOGY AND MANAGEMENT": "bmsit.ac.in",
    "BUNDELKHAND UNIVERSITY": "bujhansi.ac.in",
    // Batch 29-30
    "CALCUTTA UNIVERSITY": "caluniv.ac.in",
    "CAMBRIDGE INSTITUTE OF TECHNOLOGY": "cambridge.edu.in",
    "CAMELIA INSTITUTE OF TECHNOLOGY": "camelliait.org",
    "CANARA ENGINEERING COLLEGE": "canaraengineering.in",
    "CAPE INSTITUTE OF TECHNOLOGY": "capeitech.com",
    "CAS- COLLEGE OF ENGINEERING ATTINGAL": "ceattingal.ac.in",
    "CAS- COLLEGE OF ENGINEERING KALLOOPPARA": "cekalp.ac.in",
    "CAS- COLLEGE OF ENGINEERING KARUNAGAPPALLY": "cekp.ac.in",
    "CAS- COLLEGE OF ENGINEERING POONJAR": "cep.ac.in",
    "CAS-COLLEGE OF ENGINEERING ADOOR": "cea.ac.in",
    "CAS-COLLEGE OF ENGINEERING CHERTHALA": "cecherthala.ac.in",
    "CAV -COLLEGE OF ENGINEERING CHENGANNUR": "ceconline.edu",
    "COCHIN UNIVERSITY OF SCIENCE AND TECHNOLOGY": "cusat.ac.in",
    "CENTRAL UNIVERSITY OF HARYANA": "cuh.ac.in",
    "CENTRAL UNIVERSITY OF PUNJAB": "cup.edu.in",
    "CENTRAL UNIVERSITY OF RAJASTHAN": "curaj.ac.in",
    "CH. DEVI LAL STATE INSTITUTE OF ENGINEERING & TECHNOLOGY": "cdlsiet.ac.in",
    "CHAMELI DEVI GROUP OF INSTITUTIONS": "cdgi.edu.in",
    "CHANDUBHAI S. PATEL INSTITUTE OF TECHNOLOGY": "charusat.ac.in",
    "CHAROTAR UNIVERSITY OF SCIENCE AND TECHNOLOGY": "charusat.ac.in",
    "CHITKARA UNIVERSITY": "chitkara.edu.in",
    "COIMBATORE INSTITUTE OF TECHNOLOGY": "cit.edu.in",
    "CHRIST (DEEMED TO BE UNIVERSITY)": "christuniversity.in",
    "CHRIST COLLEGE OF ENGINEERING": "cce.edu.in",
    // Batch 31-32
    "COLLEGE OF ENGINEERING AND MANAGEMENT, KOLAGHAT": "cemkolaghat.org",
    "COLLEGE OF ENGINEERING, GUINDY": "ceg.annauniv.edu",
    "COORG INSTITUTE OF TECHNOLOGY": "citcoorg.edu.in",
    "CSI COLLEGE OF ENGINEERING": "csice.edu.in",
    "CUMMINS COLLEGE OF ENGINEERING FOR WOMEN": "cumminscollege.org",
    "DAYANANDA SAGAR COLLEGE OF ENGINEERING": "dsce.edu.in",
    "DEENBANDHU CHHOTU RAM UNIVERSITY OF SCIENCE AND TECHNOLOGY": "dcrustm.ac.in",
    "DELHI TECHNOLOGICAL UNIVERSITY": "dtu.ac.in",
    "DEVI AHILYA VISHWAVIDYALAYA": "dauniv.ac.in",
    "DON BOSCO COLLEGE OF ENGINEERING": "dbcegoa.ac.in",
    "DR BABASAHEB AMBEDKAR TECHNOLOGICAL UNIVERSITY LONERE": "dbatu.ac.in",
    "DR. B. R. AMBEDKAR NATIONAL INSTITUTE OF TECHNOLOGY JALANDHAR": "nitj.ac.in",
    "DR. B.C. ROY ENGINEERING COLLEGE": "bcrec.ac.in",
    "DR. M.G.R. EDUCATIONAL AND RESEARCH INSTITUTE": "drmgrdu.ac.in",
    "DR. SUDHIR CHANDRA SUR INSTITUTE OF TECHNOLOGY AND SPORTS COMPLEX": "surtech.edu.in",
    "DR. T. THIMMAIAH INSTITUTE OF TECHNOLOGY": "drttit.edu.in",
    // Batch 33-34
    "DURGAPUR INSTITUTE OF ADVANCED TECHNOLOGY AND MANAGEMENT": "diatm.rahul.ac.in",
    "EAST WEST INSTITUTE OF TECHNOLOGY": "ewit.edu.in",
    "ENGINEERING COLLEGE AJMER": "ecajmer.ac.in",
    "ENGINEERING COLLEGE JHALAWAR": "gecj.ac.in",
    "FR. CONCEICAO RODRIGUES COLLEGE OF ENGINEERING": "frcrce.ac.in",
    "FR. CONCEICAO RODRIGUES INSTITUTE OF TECHNOLOGY": "fcrit.ac.in",
    "GALGOTIAS UNIVERSITY": "galgotiasuniversity.edu.in",
    "GANPAT UNIVERSITY": "ganpatuniversity.ac.in",
    "GHANI KHAN CHOUDHURY INSTITUTE OF ENGINEERING & TECHNOLOGY": "gkciet.ac.in",
    "GIET UNIVERSITY": "giet.edu",
    "GLOBAL ACADEMY OF TECHNOLOGY": "gat.ac.in",
    "ENGINEERING COLLEGE BIKANER": "ecb.ac.in",
    "ENGINEERING COLLEGE DHOLPUR": "ecdholpur.ac.in",
    "EXCEL ENGINEERING COLLEGE": "excelcolleges.com",
    "GALGOTIAS COLLEGE OF ENGINEERING AND TECHNOLOGY": "galgotiacollege.edu",
    "GANDHI INSTITUTE OF TECHNOLOGY AND MANAGEMENT GITAM UNIVERSITY": "gitam.edu",
    "GGS INDRAPRASTHA UNIVERSITY": "ipu.ac.in",
    "GNIT": "gnit.ac.in",
    // Batch 35-36
    "GOA COLLEGE OF ENGINEERING": "gec.ac.in",
    "GOVT COLLEGE OF ENGINEERING AMRAVATI": "gcoea.ac.in",
    "GOVERNMENT COLLEGE OF ENGINEERING AURANGABAD": "geca.ac.in",
    "GOVERNMENT COLLEGE OF ENGINEERING KANNUR": "gcek.ac.in",
    "GOVERNMENT COLLEGE OF ENGINEERING KARAD": "gcekarad.ac.in",
    "GOVERNMENT COLLEGE OF ENGINEERING KOLHAPUR": "gcekolh.ac.in",
    "GOVERNMENT COLLEGE OF ENGINEERING NAGPUR": "gcoen.ac.in",
    "GOVERNMENT COLLEGE OF ENGINEERING SRIRANGAM": "gces.edu.in",
    "GOVERNMENT COLLEGE OF ENGINEERING TIRUNELVELI": "gcetly.ac.in",
    "GOVERNMENT ENGINEERING COLLEGE BANSWARA": "gecbanswara.ac.in",
    "GOVERNMENT ENGINEERING COLLEGE BHAVNAGAR": "gecbhavnagar.ac.in",
    "GOVERNMENT ENGINEERING COLLEGE BHUJ": "gecbhuj.ac.in",
    "GOVERNMENT ENGINEERING COLLEGE DAHOD": "gecdahod.ac.in",
    "GOVERNMENT ENGINEERING COLLEGE RAIPUR": "gecraipur.ac.in",
    "GOVERNMENT ENGINEERING COLLEGE RAJKOT": "gecrajkot.ac.in",
    "GOVERNMENT ENGINEERING COLLEGE SURAT": "ssgec.cteguj.in",
    "GOVERNMENT ENGINEERING COLLEGE PATAN": "gecpatan.ac.in",
    "HALDIA INSTITUTE OF TECHNOLOGY": "hithaldia.ac.in",
    "GURU JAMBHESHWAR UNIVERSITY OF SCIENCE & TECHNOLOGY": "gjust.ac.in",
    "GURU NANAK INSTITUTE OF TECHNOLOGY": "gnit.ac.in",
    // Batch 37-38
    "IIIT AGARTALA": "iiitagartala.ac.in",
    "IIIT ALLAHABAD": "iiita.ac.in",
    "IIIT BHAGALPUR": "iiitbh.ac.in",
    "IIIT BHOPAL": "iiitbhopal.ac.in",
    "IIIT DELHI": "iiitd.ac.in",
    "IIIT DHARWAD": "iiitdwd.ac.in",
    "IIIT GUWAHATI": "iiitg.ac.in",
    "IIIT GWALIOR": "abviiitm.ac.in",
    "IIIT HYDERABAD": "iiit.ac.in",
    "IIIT JABALPUR": "iiitdmj.ac.in",
    "IIIT KALYANI": "iiitkalyani.ac.in",
    "IIIT KANCHEEPURAM": "iiitdm.ac.in",
    "IIIT KOTTAYAM": "iiitkottayam.ac.in",
    "IIIT KOTA": "iiitkota.ac.in",
    "IIIT KURUKSHETRA": "iiitkurukshetra.ac.in",
    "IIIT LUCKNOW": "iiitl.ac.in",
    "IIIT MANIPUR": "iiitmanipur.ac.in",
    "IIIT NAGPUR": "iiitn.ac.in",
    "IIIT PUNE": "iiitp.ac.in",
    "IIIT RAICHUR": "iiitraichur.ac.in",
    "IIIT RANCHI": "iiitranchi.ac.in",
    "IIIT SRI CITY": "iiits.ac.in",
    "IIIT SURAT": "iiitsurat.ac.in",
    "IIIT TIRUCHIRAPPALLI": "iiitt.ac.in",
    "IIIT UNA": "iiitu.ac.in",
    "IIIT VADODARA": "iiitvadodara.ac.in",
    "IIITB": "iiitb.ac.in",
    "IIIT-BHUBANESWAR": "iiit-bh.ac.in",
    "IIITDM KURNOOL": "iiitk.ac.in",
    // Batch 39-40
    "IIT BOMBAY": "iitb.ac.in",
    "IIT DELHI": "iitd.ac.in",
    "IIT DHANBAD": "iitism.ac.in",
    "IIT GANDHINAGAR": "iitgn.ac.in",
    "IIT GUWAHATI": "iitg.ac.in",
    "IIT HYDERABAD": "iith.ac.in",
    "IIT INDORE": "iiti.ac.in",
    "IIT JODHPUR": "iitj.ac.in",
    "IIT KANPUR": "iitk.ac.in",
    "IIT KHARAGPUR": "iitkgp.ac.in",
    "IIT MADRAS": "iitm.ac.in",
    "IIT MANDI": "iitmandi.ac.in",
    "IIT PALAKKAD": "iitpkd.ac.in",
    "IIT PATNA": "iitp.ac.in",
    "IIT ROORKEE": "iitr.ac.in",
    "IIT ROPAR": "iitrpr.ac.in",
    "IIT VARANASI": "iitbhu.ac.in",
    "INDIRA GANDHI DELHI TECHNICAL UNIVERSITY FOR WOMEN": "igdtuw.ac.in",
    "INSTITUTE OF CHEMICAL TECHNOLOGY": "ictmumbai.edu.in",
    "INSTITUTE OF ENGINEERING & MANAGEMENT": "iem.edu.in",
    "INSTITUTE OF INFRASTRUCTURE TECHNOLOGY RESEARCH AND MANAGEMENT (IITRAM)": "iitram.ac.in",
    "INDIAN INSTITUTE OF SPACE SCIENCE AND TECHNOLOGY": "iist.ac.in",
    // Batch 41 & 42
    "JADAVPUR UNIVERSITY": "jadavpuruniversity.in",
    "JAMIA MILLIA ISLAMIA": "jmi.ac.in",
    "JAWAHARLAL NEHRU TECHNOLOGICAL UNIVERSITY HYDERABAD": "jntuh.ac.in",
    "JAWAHARLAL NEHRU TECHNOLOGICAL UNIVERSITY KAKINADA": "jntuk.edu.in",
    "JAWAHARLAL NEHRU TECHNOLOGICAL UNIVERSITY ANANTAPUR": "jntua.ac.in",
    "JNTUH UNIVERSITY COLLEGE OF ENGINEERING HYDERABAD": "jntuhceh.ac.in",
    "JNTUH UNIVERSITY COLLEGE OF ENGINEERING JAGTIAL": "jntuhcej.ac.in",
    "JNTUK COLLEGE OF ENGINEERING KAKINADA": "jntukcek.ac.in",
    "JNTUK COLLEGE OF ENGINEERING NARSARAOPET": "jntukn.ac.in",
    "JNTUK COLLEGE OF ENGINEERING VIZIANAGARAM": "jntugv.edu.in",
    "JAYPEE INSTITUTE OF INFORMATION TECHNOLOGY": "jiit.ac.in",
    "JAYPEE UNIVERSITY OF ENGINEERING AND TECHNOLOGY": "juet.ac.in",
    "JECRC UNIVERSITY": "jecrcuniversity.edu.in",
    "JIS COLLEGE OF ENGINEERING": "jiscollege.ac.in",
    "JSS ACADEMY OF TECHNICAL EDUCATION": "jssaten.ac.in",
    "JSS SCIENCE AND TECHNOLOGY UNIVERSITY": "jssstuniv.in",
    "K J SOMAIYA COLLEGE OF ENGINEERING": "kjsce.somaiya.edu",
    "K. K. WAGH INSTITUTE OF ENGINEERING EDUCATION & RESEARCH": "kkwagh.edu.in",
    // Batch 43 & 44
    "KALINGA INSTITUTE OF INDUSTRIAL TECHNOLOGY": "kiit.ac.in",
    "LPU": "lpu.in",
    "L.D. COLLEGE OF ENGINEERING": "ldce.ac.in",
    "KAMLA NEHRU INSTITUTE OF TECHNOLOGY": "knit.ac.in",
    "KARPAGAM COLLEGE OF ENGINEERING": "kce.ac.in",
    "KLE TECHNOLOGICAL UNIVERSITY": "kletech.ac.in",
    "KUMARAGURU COLLEGE OF TECHNOLOGY": "kct.ac.in",
    "LAKSHMI NARAIN COLLEGE OF TECHNOLOGY": "lnct.ac.in",
    "LOYOLA ICAM COLLEGE OF ENGINEERING AND TECHNOLOGY": "licet.ac.in",
    "LUKHDHIRJI ENGINEERING COLLEGE": "lecollege.ac.in",
    // Batch 45 & 46
    "M.S. RAMAIAH INSTITUTE OF TECHNOLOGY": "msrit.edu",
    "MADAN MOHAN MALAVIYA UNIVERSITY OF TECHNOLOGY": "mmmut.ac.in",
    "MAHINDRA UNIVERSITY": "mahindrauniversity.edu.in",
    "MALAVIYA NATIONAL INSTITUTE OF TECHNOLOGY JAIPUR": "mnit.ac.in",
    "MAULANA AZAD NATIONAL INSTITUTE OF TECHNOLOGY": "manit.ac.in",
    "MANIPAL INSTITUTE OF TECHNOLOGY": "manipal.edu",
    "MALLA REDDY ENGINEERING COLLEGE": "mrec.ac.in",
    "MARWADI UNIVERSITY": "marwadiuniversity.ac.in",
    "MEDI-CAPS UNIVERSITY": "medicaps.ac.in",
    "MAULANA ABUL KALAM AZAD UNIVERSITY OF TECHNOLOGY WEST BENGAL": "wbut.ac.in",
    "MAHARAJA AGRASEN INSTITUTE OF TECHNOLOGY": "mait.ac.in",
    "MAHARAJA SURAJMAL INSTITUTE OF TECHNOLOGY": "msit.in",
    "MADHAV INSTITUTE OF TECHNOLOGY & SCIENCE": "mitsgwalior.in",
    // Batch 47-50
    "NATIONAL INSTITUTE OF TECHNOLOGY AGARTALA": "nitagartala.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY CALICUT": "nitc.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY DELHI": "nitdelhi.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY DURGAPUR": "nitdgp.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY GOA": "nitgoa.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY HAMIRPUR": "nith.ac.in",
    "NATIONAL INSTITUTE of TECHNOLOGY JAMSHEDPUR": "nitjsr.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY KARNATAKA": "nitk.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY KURUKSHETRA": "nitkkr.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY MANIPUR": "nitmanipur.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY MEGHALAYA": "nitm.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY MIZORAM": "nitmz.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY NAGALAND": "nitnagaland.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY PATNA": "nitp.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY PUDUCHERRY": "nitpy.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY RAIPUR": "nitrr.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY ROURKELA": "nitrkl.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY SIKKIM": "nitsikkim.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY SILCHAR": "nits.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY SRINAGAR": "nitsri.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY TIRUCHIRAPPALLI": "nitt.edu",
    "NATIONAL INSTITUTE OF TECHNOLOGY UTTARAKHAND": "nituk.ac.in",
    "NATIONAL INSTITUTE OF TECHNOLOGY WARANGAL": "nitw.ac.in",
    "MOTILAL NEHRU NATIONAL INSTITUTE OF TECHNOLOGY ALLAHABAD": "mnnit.ac.in",
    "NETAJI SUBHAS UNIVERSITY OF TECHNOLOGY": "nsut.ac.in",
    "NARSEE MONJEE INSTITUTE OF MANAGEMENT STUDIES": "nmims.edu",
    "NITTE MEENAKSHI INSTITUTE OF TECHNOLOGY": "nmit.ac.in",
    "P.S.G. COLLEGE OF TECHNOLOGY": "psgtech.edu",
    "NEW HORIZON COLLEGE OF ENGINEERING": "newhorizonindia.edu"
};

let data = {};
if (fs.existsSync(WEBSITES_PATH)) {
    data = JSON.parse(fs.readFileSync(WEBSITES_PATH, 'utf-8'));
}

Object.assign(data, newMappings);
fs.writeFileSync(WEBSITES_PATH, JSON.stringify(data, null, 4));
console.log('Successfully updated college_websites.json with Batch 19-40');
